function [qhat, testResults] = conformalPrediction( ...
    model, calibData, testData, featureNames)
%CONFORMALPREDICTION Lead-time-conditioned split conformal prediction.
%
% This implementation:
%   1. Predicts the calibration data.
%   2. Estimates forecast bias separately for every lead step.
%   3. Corrects calibration and test predictions using that bias.
%   4. Calculates a conformal quantile for every lead step.
%   5. Creates prediction intervals for the 96-step forecast horizon.
%
% Inputs
% ------
% model        : Trained LSBoost model
% calibData    : Chronological calibration split
% testData     : Chronological testing split
% featureNames : Predictor names used during training
%
% Outputs
% -------
% qhat         : Global conformal quantile, retained for summary reporting
% testResults  : Test table containing actual power, corrected forecast,
%                residuals, lower/upper bounds, and coverage indicators

    disp("Applying lead-time-conditioned split conformal prediction...");

    %% Configuration

    alpha = 0.10;       % Nominal 90% prediction intervals
    numberOfLeads = 96;

    %% Validate required variables

    requiredVariables = [ ...
        featureNames, ...
        { ...
            'target_power', ...
            'forecast_origin_time', ...
            'target_timestamp', ...
            'lead_step', ...
            'lead_hours' ...
        } ...
    ];

    missingCalibVariables = setdiff( ...
        requiredVariables, ...
        calibData.Properties.VariableNames);

    missingTestVariables = setdiff( ...
        requiredVariables, ...
        testData.Properties.VariableNames);

    if ~isempty(missingCalibVariables)
        error( ...
            "Calibration data is missing variables: %s", ...
            strjoin(missingCalibVariables, ", "));
    end

    if ~isempty(missingTestVariables)
        error( ...
            "Test data is missing variables: %s", ...
            strjoin(missingTestVariables, ", "));
    end

    %% Calibration predictions

    XCalib = calibData(:, featureNames);
    yCalib = calibData.target_power;

    yCalibPredRaw = predict(model, XCalib);
    yCalibPredRaw = max(yCalibPredRaw, 0);

    rawCalibResidual = yCalib - yCalibPredRaw;

    %% Global bias and conformal quantile
    %
    % These values are retained for overall summary reporting.

    globalBias = median(rawCalibResidual, 'omitnan');

    yCalibPredGlobalCorrected = ...
        max(yCalibPredRaw + globalBias, 0);

    globalScores = abs( ...
        yCalib - yCalibPredGlobalCorrected);

    globalScores = sort(globalScores);

    nGlobal = length(globalScores);

    globalOrder = ceil( ...
        (nGlobal + 1) * (1 - alpha));

    globalOrder = min(globalOrder, nGlobal);

    qhat = globalScores(globalOrder);

    %% Calculate bias and quantile for every forecast lead step

    leadBias = NaN(numberOfLeads, 1);
    leadQhat = NaN(numberOfLeads, 1);
    calibrationCount = zeros(numberOfLeads, 1);

    for lead = 1:numberOfLeads

        leadMask = calibData.lead_step == lead;

        calibrationCount(lead) = sum(leadMask);

        if calibrationCount(lead) < 20
            % Use global values when too few calibration points exist
            leadBias(lead) = globalBias;
            leadQhat(lead) = qhat;
            continue;
        end

        currentActual = yCalib(leadMask);
        currentRawPrediction = yCalibPredRaw(leadMask);

        currentResidual = ...
            currentActual - currentRawPrediction;

        % Robust bias correction using the median residual
        leadBias(lead) = median( ...
            currentResidual, ...
            'omitnan');

        currentCorrectedPrediction = max( ...
            currentRawPrediction + leadBias(lead), ...
            0);

        currentScores = abs( ...
            currentActual - currentCorrectedPrediction);

        currentScores = sort(currentScores);

        nCurrent = length(currentScores);

        currentOrder = ceil( ...
            (nCurrent + 1) * (1 - alpha));

        currentOrder = min(currentOrder, nCurrent);

        leadQhat(lead) = currentScores(currentOrder);
    end

    %% Test predictions

    XTest = testData(:, featureNames);
    yTest = testData.target_power;

    yTestPredRaw = predict(model, XTest);
    yTestPredRaw = max(yTestPredRaw, 0);

    nTest = height(testData);

    biasCorrection = NaN(nTest, 1);
    appliedQhat = NaN(nTest, 1);

    for lead = 1:numberOfLeads

        leadMask = testData.lead_step == lead;

        biasCorrection(leadMask) = leadBias(lead);
        appliedQhat(leadMask) = leadQhat(lead);
    end

    %% Apply bias correction

    yTestPred = max( ...
        yTestPredRaw + biasCorrection, ...
        0);

    %% Prediction intervals

    lower = max( ...
        yTestPred - appliedQhat, ...
        0);

    upper = yTestPred + appliedQhat;

    %% Coverage and residual statistics

    covered = ...
        yTest >= lower & ...
        yTest <= upper;

    empiricalCoverage = mean(covered) * 100;

    averageIntervalWidth = mean( ...
        upper - lower, ...
        'omitnan');

    correctedResidual = yTest - yTestPred;

    correctedRMSE = sqrt( ...
        mean(correctedResidual.^2, 'omitnan'));

    correctedMAE = mean( ...
        abs(correctedResidual), ...
        'omitnan');

    correctedBias = mean( ...
        correctedResidual, ...
        'omitnan');

    fprintf("Nominal coverage = %.2f %%\n", ...
        (1-alpha)*100);

    fprintf("Global calibration bias = %.2f W\n", ...
        globalBias);

    fprintf("Global conformal qhat = %.2f W\n", ...
        qhat);

    fprintf("Empirical coverage = %.2f %%\n", ...
        empiricalCoverage);

    fprintf("Average interval width = %.2f W\n", ...
        averageIntervalWidth);

    fprintf("Bias-corrected test RMSE = %.2f W\n", ...
        correctedRMSE);

    fprintf("Bias-corrected test MAE = %.2f W\n", ...
        correctedMAE);

    fprintf("Bias-corrected residual mean = %.2f W\n", ...
        correctedBias);

    %% Construct output table

    testResults = table( ...
        testData.forecast_origin_time, ...
        testData.target_timestamp, ...
        testData.lead_step, ...
        testData.lead_hours, ...
        yTest, ...
        yTestPredRaw, ...
        biasCorrection, ...
        yTestPred, ...
        correctedResidual, ...
        lower, ...
        upper, ...
        appliedQhat, ...
        covered, ...
        'VariableNames', { ...
            'forecast_origin_time', ...
            'target_timestamp', ...
            'lead_step', ...
            'lead_hours', ...
            'actual', ...
            'predicted_raw', ...
            'bias_correction', ...
            'predicted', ...
            'residual', ...
            'lower', ...
            'upper', ...
            'qhat', ...
            'covered'});

    %% Select one complete 24-hour forecast for plotting

    uniqueOrigins = unique( ...
        testResults.forecast_origin_time, ...
        'stable');

    selectedOrigin = uniqueOrigins(1);
    bestCount = 0;

    for i = 1:length(uniqueOrigins)

        currentCount = sum( ...
            testResults.forecast_origin_time == uniqueOrigins(i));

        if currentCount > bestCount
            bestCount = currentCount;
            selectedOrigin = uniqueOrigins(i);
        end
    end

    plotMask = ...
        testResults.forecast_origin_time == selectedOrigin;

    plotResults = testResults(plotMask, :);
    plotResults = sortrows(plotResults, 'lead_step');

    %% Plot conformal prediction interval

    figure;
    hold on;

    fill( ...
        [plotResults.target_timestamp; ...
         flipud(plotResults.target_timestamp)], ...
        [plotResults.upper; ...
         flipud(plotResults.lower)], ...
        [0.85 0.85 0.85], ...
        'EdgeColor', 'none', ...
        'FaceAlpha', 0.5);

    plot( ...
        plotResults.target_timestamp, ...
        plotResults.actual, ...
        'b', ...
        'LineWidth', 1.6);

    plot( ...
        plotResults.target_timestamp, ...
        plotResults.predicted, ...
        'r', ...
        'LineWidth', 1.6);

    plot( ...
        plotResults.target_timestamp, ...
        plotResults.lower, ...
        'k--', ...
        'LineWidth', 1.0);

    plot( ...
        plotResults.target_timestamp, ...
        plotResults.upper, ...
        'k--', ...
        'LineWidth', 1.0);

    xlabel('Target Timestamp');
    ylabel('PV Power (W)');

    title(sprintf( ...
        '24-Hour Forecast with Conformal Intervals: %s', ...
        string(selectedOrigin)));

    legend( ...
        'Prediction interval', ...
        'Actual', ...
        'Bias-corrected prediction', ...
        'Lower bound', ...
        'Upper bound', ...
        'Location', ...
        'best');

    grid on;
    hold off;

    %% Coverage by forecast lead time

    leadCoverage = NaN(numberOfLeads, 1);
    leadIntervalWidth = NaN(numberOfLeads, 1);

    for lead = 1:numberOfLeads

        leadMask = testResults.lead_step == lead;

        if any(leadMask)

            leadCoverage(lead) = ...
                mean(testResults.covered(leadMask)) * 100;

            leadIntervalWidth(lead) = mean( ...
                testResults.upper(leadMask) - ...
                testResults.lower(leadMask), ...
                'omitnan');
        end
    end

    leadGrid = (1:numberOfLeads)' / 4;

    figure;

    plot( ...
        leadGrid, ...
        leadCoverage, ...
        'LineWidth', ...
        1.5);

    yline( ...
        90, ...
        'k--', ...
        'Nominal coverage', ...
        'LineWidth', ...
        1.5);

    xlabel('Forecast Lead Time (hours)');
    ylabel('Empirical Coverage (%)');
    title('Conformal Coverage vs Forecast Lead Time');
    grid on;

    %% Store summary metadata

    testResults.Properties.UserData = struct( ...
        'Alpha', alpha, ...
        'NominalCoverage', (1-alpha)*100, ...
        'GlobalBias', globalBias, ...
        'GlobalQhat', qhat, ...
        'LeadBias', leadBias, ...
        'LeadQhat', leadQhat, ...
        'CalibrationCount', calibrationCount, ...
        'EmpiricalCoverage', empiricalCoverage, ...
        'AverageIntervalWidth', averageIntervalWidth, ...
        'CorrectedRMSE', correctedRMSE, ...
        'CorrectedMAE', correctedMAE, ...
        'CorrectedBias', correctedBias, ...
        'LeadCoverage', leadCoverage, ...
        'LeadIntervalWidth', leadIntervalWidth);

    disp("Lead-time-conditioned conformal prediction complete.");

end