function testResults = evaluateForecastModel(model, testData, featureNames)
%EVALUATEFORECASTMODEL Evaluate the 24-hour-ahead PV forecast model.
%
% Inputs
% ------
% model        : Trained regression model
% testData     : Testing table from splitData.m
% featureNames : Predictor variable names used during training
%
% Output
% ------
% testResults  : Table containing timestamps, predictions, actual values,
%                residuals, and forecast metadata

    disp("Evaluating 24-hour-ahead forecasting model...");

    %% Validate required variables

    requiredVariables = [ ...
        featureNames, ...
        { ...
            'target_power', ...
            'target_timestamp', ...
            'forecast_origin_time', ...
            'lead_step', ...
            'lead_hours' ...
        } ...
    ];

    missingVariables = setdiff( ...
        requiredVariables, ...
        testData.Properties.VariableNames);

    if ~isempty(missingVariables)
        error( ...
            "Test data is missing required variables: %s", ...
            strjoin(missingVariables, ", "));
    end

    %% Prepare test inputs

    XTest = testData(:, featureNames);
    yTrue = testData.target_power;

    %% Generate predictions

    yPred = predict(model, XTest);

    % PV power cannot be negative
    yPred = max(yPred, 0);

    %% Calculate residuals

    residual = yTrue - yPred;
    absoluteError = abs(residual);

    %% Evaluation metrics

    rmse = sqrt(mean(residual.^2, 'omitnan'));
    mae = mean(absoluteError, 'omitnan');
    bias = mean(residual, 'omitnan');
    residualMedian = median(residual, 'omitnan');
    residualStd = std(residual, 'omitnan');
    maxAbsoluteError = max(absoluteError);

    fprintf("RMSE = %.2f W\n", rmse);
    fprintf("MAE = %.2f W\n", mae);
    fprintf("Residual mean (bias) = %.2f W\n", bias);
    fprintf("Residual median = %.2f W\n", residualMedian);
    fprintf("Residual standard deviation = %.2f W\n", residualStd);
    fprintf("Maximum absolute error = %.2f W\n", maxAbsoluteError);

    %% Construct output results table

    testResults = table( ...
        testData.forecast_origin_time, ...
        testData.target_timestamp, ...
        testData.lead_step, ...
        testData.lead_hours, ...
        yTrue, ...
        yPred, ...
        residual, ...
        absoluteError, ...
        'VariableNames', { ...
            'forecast_origin_time', ...
            'target_timestamp', ...
            'lead_step', ...
            'lead_hours', ...
            'actual', ...
            'predicted', ...
            'residual', ...
            'absolute_error'});

    %% Plot one complete 24-hour forecast origin

    uniqueOrigins = unique( ...
        testResults.forecast_origin_time, ...
        'stable');

    if isempty(uniqueOrigins)
        warning("No forecast origins available for plotting.");
        return;
    end

    % Use the first origin containing the largest number of lead steps
    selectedOrigin = uniqueOrigins(1);
    bestCount = 0;

    for i = 1:length(uniqueOrigins)

        currentCount = sum( ...
            testResults.forecast_origin_time == uniqueOrigins(i));

        if currentCount > bestCount
            bestCount = currentCount;
            selectedOrigin = uniqueOrigins(i);
        end
    end

    plotMask = ...
        testResults.forecast_origin_time == selectedOrigin;

    originResults = testResults(plotMask, :);
    originResults = sortrows(originResults, 'lead_step');

    figure;

    plot( ...
        originResults.target_timestamp, ...
        originResults.actual, ...
        'b', ...
        'LineWidth', 1.5);

    hold on;

    plot( ...
        originResults.target_timestamp, ...
        originResults.predicted, ...
        'r', ...
        'LineWidth', 1.5);

    xlabel('Target Timestamp');
    ylabel('PV Power (W)');

    title(sprintf( ...
        '24-Hour-Ahead PV Forecast Issued at %s', ...
        string(selectedOrigin)));

    legend( ...
        'Actual', ...
        'Predicted', ...
        'Location', ...
        'best');

    grid on;
    hold off;

    %% Residual histogram

    figure;

    histogram( ...
        testResults.residual, ...
        50);

    xline( ...
        0, ...
        'k--', ...
        'LineWidth', ...
        1.5);

    xline( ...
        bias, ...
        'r--', ...
        'LineWidth', ...
        1.5);

    xlabel('Residual: Actual - Predicted (W)');
    ylabel('Count');
    title('Residual Distribution');

    legend( ...
        'Residuals', ...
        'Zero residual', ...
        sprintf('Mean residual = %.1f W', bias), ...
        'Location', ...
        'best');

    grid on;

    %% Residual versus forecast lead time

    figure;

    scatter( ...
        testResults.lead_hours, ...
        testResults.residual, ...
        8, ...
        'filled');

    yline( ...
        0, ...
        'k--', ...
        'LineWidth', ...
        1.5);

    xlabel('Forecast Lead Time (hours)');
    ylabel('Residual: Actual - Predicted (W)');
    title('Residuals vs Forecast Lead Time');

    grid on;

    %% Error by lead-hour bin

    leadGrid = (0.25:0.25:24)';

    leadRMSE = NaN(length(leadGrid), 1);
    leadMAE = NaN(length(leadGrid), 1);
    leadBias = NaN(length(leadGrid), 1);

    for i = 1:length(leadGrid)

        currentMask = ...
            abs(testResults.lead_hours - leadGrid(i)) < 1e-9;

        if any(currentMask)

            currentResiduals = ...
                testResults.residual(currentMask);

            leadRMSE(i) = sqrt( ...
                mean(currentResiduals.^2, 'omitnan'));

            leadMAE(i) = mean( ...
                abs(currentResiduals), ...
                'omitnan');

            leadBias(i) = mean( ...
                currentResiduals, ...
                'omitnan');
        end
    end

    figure;

    plot( ...
        leadGrid, ...
        leadRMSE, ...
        '-o', ...
        'LineWidth', ...
        1.5);

    hold on;

    plot( ...
        leadGrid, ...
        leadMAE, ...
        '-s', ...
        'LineWidth', ...
        1.5);

    xlabel('Forecast Lead Time (hours)');
    ylabel('Error (W)');
    title('Forecast Error vs Lead Time');

    legend( ...
        'RMSE', ...
        'MAE', ...
        'Location', ...
        'best');

    grid on;
    hold off;

    %% Store metrics as table metadata

    testResults.Properties.UserData = struct( ...
        'RMSE', rmse, ...
        'MAE', mae, ...
        'Bias', bias, ...
        'ResidualMedian', residualMedian, ...
        'ResidualStd', residualStd, ...
        'MaxAbsoluteError', maxAbsoluteError, ...
        'LeadGrid', leadGrid, ...
        'LeadRMSE', leadRMSE, ...
        'LeadMAE', leadMAE, ...
        'LeadBias', leadBias);

    disp("Forecast evaluation complete.");

end