function plotFaultDetection(results, faultName, daysBefore, daysAfter)
%PLOTFAULTDETECTION Plot one fault scenario around its start time.

    if nargin < 3
        daysBefore = 2;
    end

    if nargin < 4
        daysAfter = 7;
    end

    info = results.Properties.UserData;

    faultStartTime = info.FaultStartTime;
    detectionTime = info.DetectionTime;

    plotMask = ...
        results.target_timestamp >= faultStartTime - days(daysBefore) & ...
        results.target_timestamp <= faultStartTime + days(daysAfter);

    plotData = results(plotMask, :);

    %% Power and interval plot

    figure;
    hold on;

    plot( ...
        plotData.target_timestamp, ...
        plotData.actual_faulty, ...
        'b', ...
        'LineWidth', 1.3);

    plot( ...
        plotData.target_timestamp, ...
        plotData.predicted, ...
        'r', ...
        'LineWidth', 1.3);

    plot( ...
        plotData.target_timestamp, ...
        plotData.lower, ...
        'k--', ...
        'LineWidth', 1.1);

    xline( ...
        faultStartTime, ...
        'm--', ...
        'Fault start', ...
        'LineWidth', 1.5);

    if ~isnat(detectionTime)
        xline( ...
            detectionTime, ...
            'g--', ...
            'Detection', ...
            'LineWidth', 1.5);
    end

    alarmMask = plotData.alarm_event;

    scatter( ...
        plotData.target_timestamp(alarmMask), ...
        plotData.actual_faulty(alarmMask), ...
        45, ...
        'ro', ...
        'LineWidth', 1.3);

    xlabel('Time');
    ylabel('PV Power (W)');
    title(sprintf('%s Detection Using CUSUM', faultName));

    legend( ...
        'Faulty measured power', ...
        'Forecast', ...
        'Conformal lower bound', ...
        'Fault start', ...
        'Detection', ...
        'CUSUM alarm event', ...
        'Location', ...
        'best');

    grid on;
    hold off;

    %% CUSUM statistic plot

    figure;
    hold on;

    plot( ...
        plotData.target_timestamp, ...
        plotData.cusum_statistic, ...
        'LineWidth', 1.4);

    yline( ...
        info.DecisionThreshold, ...
        'r--', ...
        'Decision threshold', ...
        'LineWidth', 1.5);

    xline( ...
        faultStartTime, ...
        'm--', ...
        'Fault start', ...
        'LineWidth', 1.5);

    if ~isnat(detectionTime)
        xline( ...
            detectionTime, ...
            'g--', ...
            'Detection', ...
            'LineWidth', 1.5);
    end

    xlabel('Time');
    ylabel('CUSUM statistic');
    title(sprintf('%s CUSUM Monitoring Statistic', faultName));

    grid on;
    hold off;

end