function monitoringResults = prepareMonitoringStream(testResults)
%PREPAREMONITORINGSTREAM Create one chronological day-ahead prediction
%per target timestamp from overlapping 96-step forecasts.
%
% For each target timestamp, the function selects the available prediction
% with the greatest lead time not exceeding 24 hours. Because forecast
% origins occur several times per day, this generally creates a continuous
% 15-minute monitoring stream using approximately 18–24-hour-ahead
% forecasts.
%
% Input
% -----
% testResults : Output table from conformalPrediction.m
%
% Output
% ------
% monitoringResults : Chronological table with one row per target timestamp.

    disp("Preparing chronological day-ahead monitoring stream...");

    %% Required variables

    requiredVariables = { ...
        'forecast_origin_time', ...
        'target_timestamp', ...
        'lead_step', ...
        'lead_hours', ...
        'actual', ...
        'predicted', ...
        'lower', ...
        'upper'};

    missingVariables = setdiff( ...
        requiredVariables, ...
        testResults.Properties.VariableNames);

    if ~isempty(missingVariables)
        error( ...
            "testResults is missing required variables: %s", ...
            strjoin(missingVariables, ", "));
    end

    %% Remove invalid rows

    validRows = ...
        ~ismissing(testResults.target_timestamp) & ...
        ~ismissing(testResults.actual) & ...
        ~ismissing(testResults.predicted) & ...
        ~ismissing(testResults.lower) & ...
        ~ismissing(testResults.upper) & ...
        testResults.lead_hours > 0 & ...
        testResults.lead_hours <= 24;

    workingResults = testResults(validRows, :);

    if isempty(workingResults)
        error("No valid rows remain for monitoring.");
    end

    %% Sort by target time and descending lead time
    %
    % Sorting lead time in descending order ensures that the first row for
    % each target timestamp is the longest available day-ahead forecast.

    workingResults = sortrows( ...
        workingResults, ...
        {'target_timestamp', 'lead_hours'}, ...
        {'ascend', 'descend'});

    %% Keep one prediction per target timestamp

    [~, selectedIndices] = unique( ...
        workingResults.target_timestamp, ...
        'first');

    monitoringResults = workingResults( ...
        sort(selectedIndices), :);

    monitoringResults = sortrows( ...
        monitoringResults, ...
        'target_timestamp');

    %% Recalculate residuals for consistency

    monitoringResults.residual = ...
        monitoringResults.actual - ...
        monitoringResults.predicted;

    monitoringResults.absolute_error = ...
        abs(monitoringResults.residual);

    %% Check timestamp spacing

    timeDifferences = minutes( ...
        diff(monitoringResults.target_timestamp));

    if isempty(timeDifferences)
        medianInterval = NaN;
    else
        medianInterval = median( ...
            timeDifferences, ...
            'omitnan');
    end

    %% Report summary

    fprintf("Original forecast rows: %d\n", ...
        height(testResults));

    fprintf("Unique monitoring timestamps: %d\n", ...
        height(monitoringResults));

    fprintf("Monitoring period: %s to %s\n", ...
        string(min(monitoringResults.target_timestamp)), ...
        string(max(monitoringResults.target_timestamp)));

    fprintf("Selected lead-time range: %.2f to %.2f hours\n", ...
        min(monitoringResults.lead_hours), ...
        max(monitoringResults.lead_hours));

    fprintf("Median monitoring interval: %.2f minutes\n", ...
        medianInterval);

    %% Plot selected lead times

    figure;

    plot( ...
        monitoringResults.target_timestamp, ...
        monitoringResults.lead_hours, ...
        'LineWidth', 1.2);

    xlabel('Target Timestamp');
    ylabel('Selected Forecast Lead Time (hours)');
    title('Lead Times Used in the Monitoring Stream');
    grid on;

    disp("Monitoring stream preparation complete.");

end