function [model, featureNames] = trainForecastModel(trainData)

disp("Training forecasting model...");

targetName = 'total_power';

featureNames = { ...
    'sun_zenith', ...
    'sun_azimuth', ...
    'temperature', ...
    'global_irradiance', ...
    'direct_irradiance', ...
    'diffuse_irradiance', ...
    'humidity', ...
    'hour_sin', ...
    'hour_cos', ...
    'day_sin', ...
    'day_cos'};

XTrain = trainData(:, featureNames);
yTrain = trainData.(targetName);

model = fitrensemble( ...
    XTrain, ...
    yTrain, ...
    'Method','LSBoost', ...
    'NumLearningCycles',100, ...
    'LearnRate',0.1);

disp("Forecasting model training complete.");

end